### ISSUE TITLE
Long words in description break table layout

### ISSUE THREAD

**Issue by Phil-Ah** [scm-manager/scm-history-download-plugin#5]
## Issue description

If you found a bug or want to have a new feature implemented, please take your time and look whether this issue has been discussed in another issue or on our mailing list already.

SCM-Manager is open source. If you have any knowledge of programming, maybe you can help. We would love to support you.

#### Describe how to reproduce the bug

Enter a commit with a very long word in the description. Visit the code-section in SCM-Manager and find a file changed by said commit. Open the history in the table. The table-cell will break the layout

#### Describe your SCM-Manager setup

SCM History Download Plugin

#### Which operating system, browser and versions do you use?

Windows, Mac or Linux? Chrome, Firefox or IE? What versions?

#### Log of the bug

Please remember to check for any sensible information in any logs you provide like repository names!
Consider to use the [support plugin](https://scm-manager.org/plugins/scm-support-plugin/) to easily create trace logs.

**Comment by eheimbuch** [comment]
Resolved by #6
